### ISSUE TITLE
Simplify generated CSS

### ISSUE THREAD

**Issue by newyankeecodeshop** [wingspan/wingspan-forms#82]
The form.less file has some rules in it that make things consistent for multiple related widgets, such as Combo & DropDown or DatePicker, TimePicker, and DateTimePicker. However, the less rule configuration causes an explosion of CSS rules to be generated, some of which are not possible to have in real DOM. For example:
```css
.formFieldDatepicker.formFieldReadonly .k-timepicker:hover .k-picker-wrap .k-input,
.formFieldTimepicker.formFieldReadonly .k-timepicker:hover .k-picker-wrap .k-input,
.formFieldDatetimepicker.formFieldReadonly .k-timepicker:hover .k-picker-wrap .k-input,
.formFieldDatepicker.formFieldReadonly .k-datepicker:hover .k-picker-wrap .k-input,
.formFieldTimepicker.formFieldReadonly .k-datepicker:hover .k-picker-wrap .k-input,
.formFieldDatetimepicker.formFieldReadonly .k-datepicker:hover .k-picker-wrap .k-input,
.formFieldDatepicker.formFieldReadonly .k-datetimepicker:hover .k-picker-wrap .k-input,
.formFieldTimepicker.formFieldReadonly .k-datetimepicker:hover .k-picker-wrap .k-input,
.formFieldDatetimepicker.formFieldReadonly .k-datetimepicker:hover .k-picker-wrap .k-input,
.formFieldDatepicker.formFieldReadonly .k-timepicker:focus .k-picker-wrap .k-input,
.formFieldTimepicker.formFieldReadonly .k-timepicker:focus .k-picker-wrap .k-input,
.formFieldDatetimepicker.formFieldReadonly .k-timepicker:focus .k-picker-wrap .k-input,
.formFieldDatepicker.formFieldReadonly .k-datepicker:focus .k-picker-wrap .k-input,
.formFieldTimepicker.formFieldReadonly .k-datepicker:focus .k-picker-wrap .k-input,
.formFieldDatetimepicker.formFieldReadonly .k-datepicker:focus .k-picker-wrap .k-input,
.formFieldDatepicker.formFieldReadonly .k-datetimepicker:focus .k-picker-wrap .k-input,
.formFieldTimepicker.formFieldReadonly .k-datetimepicker:focus .k-picker-wrap .k-input,
.formFieldDatetimepicker.formFieldReadonly .k-datetimepicker:focus .k-picker-wrap .k-input {
  background: #eeeeee;
  color: #aaaaaa;
}
```
I think we can do better.

There are also some global styles we are setting that should be left up to the application, for example:
```css

html, body {
	height: 100%;
}

body {
	font-size: .75em;
	font-family: sans-serif;
	overflow: hidden;
}
```
In general, we should not be changing OOTB element styles in this library.
